"""Configuration helpers for Lighter testnet trading."""

from __future__ import annotations

import os
from dataclasses import dataclass
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Any, Dict, Iterable, Optional, Sequence, Tuple, Union

import lighter
import yaml
from dotenv import load_dotenv


TESTNET_BASE_URL = "https://testnet.zklighter.elliot.ai"
MAINNET_BASE_URL = "https://mainnet.zklighter.elliot.ai"
DEFAULT_TRADING_CONFIG_PATH = Path("configs/lighter_trading.yml")
DEFAULT_ENV_PATH = Path(".env")

DecimalLike = Union[str, int, float, Decimal]


class LighterConfigError(ValueError):
    """Raised when Lighter trading config is incomplete or unsafe."""


@dataclass(frozen=True)
class EnvVarSpec:
    name: str
    description: str


REQUIRED_TRADING_ENV_SPECS: Tuple[EnvVarSpec, ...] = (
    EnvVarSpec("LIGHTER_ACCOUNT_INDEX", "Lighter account/subaccount index used for signed trading."),
    EnvVarSpec("LIGHTER_API_KEY_INDEX", "Lighter API key slot registered on the account."),
    EnvVarSpec("LIGHTER_API_PRIVATE_KEY", "Private key generated by lighter.create_api_key()."),
)

API_KEY_SETUP_ENV_SPECS: Tuple[EnvVarSpec, ...] = (
    EnvVarSpec("LIGHTER_ETH_PRIVATE_KEY", "L1 wallet private key used only to register or rotate a Lighter API key."),
)

OPTIONAL_ENV_SPECS: Tuple[EnvVarSpec, ...] = (
    EnvVarSpec("LIGHTER_NETWORK", "Network label. Defaults to testnet."),
    EnvVarSpec("LIGHTER_BASE_URL", "REST base URL. Defaults to the official Lighter testnet URL."),
    EnvVarSpec("LIGHTER_MARKET_PROFILE", "Market profile from configs/lighter_trading.yml. Defaults to eth_perp."),
    EnvVarSpec("LIGHTER_NONCE_MANAGEMENT", "optimistic, api, or none. Defaults to optimistic."),
    EnvVarSpec("LIGHTER_ALLOW_MAINNET", "Set true to permit mainnet URLs. Defaults to false."),
)


def _empty_to_none(value: Optional[str]) -> Optional[str]:
    if value is None:
        return None
    value = value.strip()
    return value or None


def _env(name: str, default: Optional[Any] = None) -> Optional[str]:
    value = _empty_to_none(os.getenv(name))
    if value is None:
        return str(default) if default is not None else None
    return value


def _to_int(value: Optional[Any], name: str) -> Optional[int]:
    if value is None or value == "":
        return None
    try:
        return int(value)
    except (TypeError, ValueError) as exc:
        raise LighterConfigError(f"{name} must be an integer") from exc


def _to_bool(value: Optional[Any], default: bool = False) -> bool:
    if value is None or value == "":
        return default
    if isinstance(value, bool):
        return value
    normalized = str(value).strip().lower()
    if normalized in {"1", "true", "yes", "y", "on"}:
        return True
    if normalized in {"0", "false", "no", "n", "off"}:
        return False
    raise LighterConfigError(f"Invalid boolean value: {value}")


def _to_decimal(value: Optional[Any], name: str) -> Decimal:
    if value is None or value == "":
        raise LighterConfigError(f"{name} is required")
    try:
        return Decimal(str(value))
    except (InvalidOperation, ValueError) as exc:
        raise LighterConfigError(f"{name} must be a decimal number") from exc


def _load_yaml(path: Path) -> Dict[str, Any]:
    if not path.exists():
        raise LighterConfigError(f"Missing Lighter trading config: {path}")
    with open(path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    if not isinstance(data, dict):
        raise LighterConfigError(f"Lighter trading config must be a mapping: {path}")
    return data


def decimal_to_scaled_int(value: DecimalLike, decimals: int, field_name: str = "value") -> int:
    """Convert a human decimal value into Lighter integer units without rounding."""

    if decimals < 0:
        raise LighterConfigError(f"{field_name} decimals cannot be negative")
    amount = _to_decimal(value, field_name)
    scaled = amount * (Decimal(10) ** decimals)
    integral = scaled.to_integral_value()
    if scaled != integral:
        raise LighterConfigError(
            f"{field_name}={value} has more than {decimals} supported decimals"
        )
    return int(integral)


@dataclass(frozen=True)
class LighterMarketConfig:
    symbol: str
    market_type: str
    market_index: int
    size_decimals: int
    price_decimals: int
    min_base_amount: Decimal
    min_quote_amount: Decimal

    def base_amount_to_int(self, value: DecimalLike) -> int:
        return decimal_to_scaled_int(value, self.size_decimals, "base_amount")

    def price_to_int(self, value: DecimalLike) -> int:
        return decimal_to_scaled_int(value, self.price_decimals, "price")

    def assert_min_base_amount(self, value: DecimalLike) -> None:
        amount = _to_decimal(value, "base_amount")
        if amount < self.min_base_amount:
            raise LighterConfigError(
                f"base_amount={amount} is below {self.symbol} {self.market_type} "
                f"minimum {self.min_base_amount}"
            )


@dataclass(frozen=True)
class LighterTradingConfig:
    network: str
    base_url: str
    websocket_path: str
    nonce_management: str
    allow_mainnet: bool
    account_index: Optional[int]
    api_key_index: Optional[int]
    api_private_key: Optional[str]
    eth_private_key: Optional[str]
    market_profile: str
    market: LighterMarketConfig

    @property
    def websocket_url(self) -> str:
        host = self.base_url.rstrip("/")
        if host.startswith("https://"):
            host = "wss://" + host[len("https://") :]
        elif host.startswith("http://"):
            host = "ws://" + host[len("http://") :]
        return f"{host}{self.websocket_path}"

    @property
    def has_trading_credentials(self) -> bool:
        return all(
            value is not None
            for value in (self.account_index, self.api_key_index, self.api_private_key)
        )

    def validate_network_safety(self) -> None:
        base_url = self.base_url.lower()
        if "mainnet" in base_url and not self.allow_mainnet:
            raise LighterConfigError(
                "Refusing to use a mainnet Lighter URL while LIGHTER_ALLOW_MAINNET is false"
            )
        if self.network.lower() == "testnet" and "testnet" not in base_url and not self.allow_mainnet:
            raise LighterConfigError(
                f"LIGHTER_NETWORK=testnet requires a testnet URL, got {self.base_url}"
            )

    def require_trading_credentials(self) -> None:
        missing = missing_env_names(REQUIRED_TRADING_ENV_SPECS)
        if missing:
            raise LighterConfigError(
                "Missing required Lighter trading environment variables: "
                + ", ".join(missing)
            )

    def require_eth_private_key(self) -> None:
        if self.eth_private_key is None:
            raise LighterConfigError("LIGHTER_ETH_PRIVATE_KEY is required for API key setup")

    def api_private_keys(self) -> Dict[int, str]:
        self.require_trading_credentials()
        assert self.api_key_index is not None
        assert self.api_private_key is not None
        return {self.api_key_index: self.api_private_key}

    def nonce_manager_type(self):
        normalized = self.nonce_management.lower()
        mapping = {
            "optimistic": lighter.nonce_manager.NonceManagerType.OPTIMISTIC,
            "api": lighter.nonce_manager.NonceManagerType.API,
            "none": lighter.nonce_manager.NonceManagerType.NONE,
        }
        if normalized not in mapping:
            raise LighterConfigError(
                "LIGHTER_NONCE_MANAGEMENT must be one of: optimistic, api, none"
            )
        return mapping[normalized]

    def create_api_client(self) -> lighter.ApiClient:
        self.validate_network_safety()
        return lighter.ApiClient(configuration=lighter.Configuration(host=self.base_url))

    def create_signer_client(self) -> lighter.SignerClient:
        self.validate_network_safety()
        self.require_trading_credentials()
        assert self.account_index is not None
        return lighter.SignerClient(
            url=self.base_url,
            account_index=self.account_index,
            api_private_keys=self.api_private_keys(),
            nonce_management_type=self.nonce_manager_type(),
        )


def load_lighter_trading_config(
    config_path: Union[str, Path] = DEFAULT_TRADING_CONFIG_PATH,
    env_path: Union[str, Path] = DEFAULT_ENV_PATH,
    *,
    load_env_file: bool = True,
) -> LighterTradingConfig:
    """Load Lighter trading config from YAML plus environment variables."""

    config_path = Path(config_path)
    env_path = Path(env_path)
    if load_env_file:
        load_dotenv(env_path, override=False)

    raw = _load_yaml(config_path)
    market_profile = _env("LIGHTER_MARKET_PROFILE", raw.get("default_market", "eth_perp"))
    assert market_profile is not None
    markets = raw.get("markets") or {}
    if market_profile not in markets:
        raise LighterConfigError(
            f"Unknown LIGHTER_MARKET_PROFILE={market_profile}. Available: {sorted(markets)}"
        )

    market_raw = markets[market_profile] or {}
    market = LighterMarketConfig(
        symbol=str(_env("LIGHTER_MARKET_SYMBOL", market_raw.get("symbol", "ETH"))).upper(),
        market_type=str(_env("LIGHTER_MARKET_TYPE", market_raw.get("market_type", "perp"))),
        market_index=_to_int(
            _env("LIGHTER_MARKET_INDEX", market_raw.get("market_index")),
            "LIGHTER_MARKET_INDEX",
        )
        or 0,
        size_decimals=_to_int(
            _env("LIGHTER_SIZE_DECIMALS", market_raw.get("size_decimals")),
            "LIGHTER_SIZE_DECIMALS",
        )
        or 0,
        price_decimals=_to_int(
            _env("LIGHTER_PRICE_DECIMALS", market_raw.get("price_decimals")),
            "LIGHTER_PRICE_DECIMALS",
        )
        or 0,
        min_base_amount=_to_decimal(
            _env("LIGHTER_MIN_BASE_AMOUNT", market_raw.get("min_base_amount", "0")),
            "LIGHTER_MIN_BASE_AMOUNT",
        ),
        min_quote_amount=_to_decimal(
            _env("LIGHTER_MIN_QUOTE_AMOUNT", market_raw.get("min_quote_amount", "0")),
            "LIGHTER_MIN_QUOTE_AMOUNT",
        ),
    )

    cfg = LighterTradingConfig(
        network=str(_env("LIGHTER_NETWORK", raw.get("network", "testnet"))),
        base_url=str(_env("LIGHTER_BASE_URL", raw.get("base_url", TESTNET_BASE_URL))).rstrip("/"),
        websocket_path=str(raw.get("websocket_path", "/stream")),
        nonce_management=str(_env("LIGHTER_NONCE_MANAGEMENT", raw.get("nonce_management", "optimistic"))),
        allow_mainnet=_to_bool(_env("LIGHTER_ALLOW_MAINNET", raw.get("allow_mainnet", False))),
        account_index=_to_int(_env("LIGHTER_ACCOUNT_INDEX"), "LIGHTER_ACCOUNT_INDEX"),
        api_key_index=_to_int(_env("LIGHTER_API_KEY_INDEX"), "LIGHTER_API_KEY_INDEX"),
        api_private_key=_env("LIGHTER_API_PRIVATE_KEY"),
        eth_private_key=_env("LIGHTER_ETH_PRIVATE_KEY"),
        market_profile=market_profile,
        market=market,
    )
    cfg.validate_network_safety()
    return cfg


def missing_env_names(specs: Sequence[EnvVarSpec]) -> Tuple[str, ...]:
    return tuple(spec.name for spec in specs if _empty_to_none(os.getenv(spec.name)) is None)


def env_value_status(specs: Iterable[EnvVarSpec]) -> Tuple[Tuple[EnvVarSpec, bool], ...]:
    return tuple((spec, _empty_to_none(os.getenv(spec.name)) is not None) for spec in specs)
