type: object
required:
  - experiment
  - bars
  - features
  - model
properties:
  experiment:
    type: object
    required: [id, seed, trials]
    properties:
      id:
        type: string
      seed:
        type: integer
      trials:
        type: integer
  bars:
    type: object
    required: [type]
    properties:
      type:
        type: string
        enum: [time, tick, volume, dollar]
      threshold_usd:
        type: number
      threshold_ticks:
        type: integer
      threshold_volume:
        type: number
      time_interval:
        type: string
        pattern: '^[0-9]+[mhd]$'
  features:
    type: object
    required: [frac_diff_order, include]
    properties:
      frac_diff_order:
        type: number
        minimum: 0
        maximum: 1
      include:
        type: array
        items:
          type: string
          enum: [vol_adj_flow, rsi, macd, bollinger, volume_profile]
  model:
    type: object
    required: [level0]
    properties:
      level0:
        type: object
        required: [algo, params]
        properties:
          algo:
            type: string
            enum: [xgboost, lightgbm, catboost]
          params:
            type: object
            properties:
              max_depth:
                type: integer
                minimum: 1
              eta:
                type: number
                minimum: 0
              tree_method:
                type: string
                enum: [gpu_hist, hist, exact]
      meta_labeling:
        type: boolean
  market_maker:
    type: object
    properties:
      gamma:
        type: number
        minimum: 0
      hedge:
        type: boolean
      inventory_limit:
        type: number
      quote_spread:
        type: number
        minimum: 0
  bribe:
    type: object
    required: [mode]
    properties:
      mode:
        type: string
        enum: [percentile, fixed, adaptive]
      percentile:
        type: number
        minimum: 0
        maximum: 100
      fixed_amount:
        type: number
        minimum: 0
  backtest:
    type: object
    required: [start, end, initial_capital]
    properties:
      start:
        type: string
        format: date
      end:
        type: string
        format: date
      initial_capital:
        type: number
        minimum: 0
  sim:
    type: object
    required: [mode]
    properties:
      mode:
        type: string
        enum: [amm, lob]
      seed:
        type: integer
      amm:
        type: object
        properties:
          fee_bps:
            type: integer
            minimum: 0
            maximum: 10000
          inventory:
            type: number
      lob:
        type: object
        properties:
          tick_size:
            type: number
            minimum: 0
          depth_levels:
            type: integer
            minimum: 1
